version: '3'

services:
  salzc:
    image: schweigert/tcc:salzc_v006
    command: salzc
    environment:
      - SALZWEB_URL=http://10.20.218.242:3000
      - SALZA_ADDR=10.20.218.242:3001
      - SALZCHAT_ADDR=10.20.218.242:3002
      - SALZGH_ADDR=10.20.218.242:3003
      - RUDYWEB_URL=http://10.20.218.242:3003
      - RUDYGH_ADDR=10.20.218.242:3002
      - GRAPHITE_PORT=2003
      - GRAPHITE_ADDR=10.20.218.244