version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    logging:
      driver: none

  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    logging:
      driver: none
