version: '3'

services:

  rudyc:
    build:
      context: ../.
      dockerfile: build/rudyc/Dockerfile
    command: rudyc
    environment:
      - RUDYWEB_URL=http://rudyweb
      - RUDYGH_ADDR=rudygh:3000
      - GRAPHITE_PORT=2003
      - GRAPHITE_ADDR=graphite
    depends_on:
      - rudyweb


  rudya:
    build:
      context: ../.
      dockerfile: build/rudya/Dockerfile
    command: rudya
    environment:
      - ADDR=0.0.0.0:3000
      - RUDYDB_ADDR=http://rudydb
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  rudydb:
    build:
      context: ../.
      dockerfile: build/rudydb/Dockerfile
    command: rudydb
    environment:
      - ADDR=0.0.0.0:80
      - GIN_MODE=debug
      - DB_CONFIG=host=postgres port=5432 user=postgres password=postgres sslmode=disable dbname=game
    ports:
      - 3001:80
    depends_on:
      - postgres

  rudygh:
    build:
      context: ../.
      dockerfile: build/rudygh/Dockerfile
    command: rudygh
    environment:
      - ADDR=0.0.0.0:3000
      - RUDYA_ADDR=rudya:3000
    depends_on:
      - postgres

  rudyweb:
    build:
      context: ../.
      dockerfile: build/rudyweb/Dockerfile
    command: rudyweb
    environment:
      - ADDR=0.0.0.0:80
      - GIN_MODE=debug
      - RUDYDB_ADDR=http://rudydb
    ports:
      - 3000:80
    depends_on:
      - rudydb
      - rudya

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    logging:
      driver: none

  postgres:
    image: postgres:9.6
    ports:
      - 5432
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    logging:
      driver: none

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 5050:3000
    volumes:
      - grafana-volume
    logging:
      driver: none

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - 2003:2003
    restart: always
    logging:
      driver: none

volumes:
  grafana-volume:
    external: true
