version: '3'

services:
  rudya:
    image: schweigert/tcc:rudya_v001
    command: rudya
    environment:
      - ADDR=0.0.0.0:3000
      - RUDYDB_ADDR=http://rudydb:3001
      - REDIS_ADDR=192.168.3.11:6379
    ports:
      - 3000

  rudydb:
    image: schweigert/tcc:rudydb_v001
    command: rudydb
    environment:
      - ADDR=0.0.0.0:3001
      - GIN_MODE=debug
      - DB_CONFIG=host=192.168.3.11 port=5432 user=postgres password=postgres sslmode=disable dbname=game
    ports:
      - 3001:3001

  rudygh:
    image: schweigert/tcc:rudygh_v001
    command: rudygh
    environment:
      - ADDR=0.0.0.0:3002
      - RUDYA_ADDR=rudya:3000
    ports:
      - 3002:3002

  rudyweb:
    image: schweigert/tcc:rudyweb_v001
    command: rudyweb
    environment:
      - ADDR=0.0.0.0:3003
      - GIN_MODE=debug
      - RUDYDB_ADDR=http://rudydb:3001
    ports:
      - 3003:3003
    depends_on:
      - rudydb
      - rudya
