version: '3'

services:
  rudya:
    image: schweigert/tcc:rudya_v001
    command: rudya
    environment:
      - ADDR=0.0.0.0:3000
      - RUDYDB_ADDR=http://rudydb
      - REDIS_ADDR=redis:6379
    ports:
      - 3000:3000
    depends_on:
      - redis

  rudydb:
    image: schweigert/tcc:rudydb_v001
    command: rudydb
    environment:
      - ADDR=0.0.0.0:80
      - GIN_MODE=debug
      - DB_CONFIG=host=postgres port=5432 user=postgres password=postgres sslmode=disable dbname=game
    ports:
      - 3001:80
    depends_on:
      - postgres

  rudygh:
    image: schweigert/tcc:rudygh_v001
    command: rudygh
    environment:
      - ADDR=0.0.0.0:3000
      - RUDYA_ADDR=rudya:3000
    ports:
      - 3002:3000
    depends_on:
      - postgres

  rudyweb:
    image: schweigert/tcc:rudyweb_v001
    command: rudyweb
    environment:
      - ADDR=0.0.0.0:80
      - GIN_MODE=debug
      - RUDYDB_ADDR=http://rudydb
    ports:
      - 3003:80
    depends_on:
      - rudydb
      - rudya

  redis:
    image: redis
    ports:
      - 6379
    logging:
      driver: none

  postgres:
    image: postgres:9.6
    ports:
      - 5432
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    logging:
      driver: none
