version: '3'

services:
  salzweb:
    image: schweigert/tcc:salzweb_v003
    command: salzweb
    environment:
      - ADDR=0.0.0.0:80
      - DB_CONFIG=host=192.168.3.11 port=5432 user=postgres password=postgres sslmode=disable dbname=game
    ports:
      - "3000:80"

  salza:
    image: schweigert/tcc:salza_v003
    command: salza
    environment:
      - ADDR=0.0.0.0:3000
      - DB_CONFIG=host=192.168.3.11 port=5432 user=postgres password=postgres sslmode=disable dbname=game
      - REDIS_ADDR=192.168.3.11:6379
    ports:
      - "3001:3000"

  salzchat:
    image: schweigert/tcc:salzchat_v003
    command: salzchat
    environment:
      - ADDR=0.0.0.0:3000
      - SALZA_ADDR=salza:3000
    depends_on:
      - salza
    ports:
      - "3002:3000"

  salzgh:
    image: schweigert/tcc:salzgh_v003
    command: salzgh
    environment:
      - ADDR=0.0.0.0:3000
      - SALZA_ADDR=salza:3000
    depends_on:
      - salza
    ports:
      - "3003:3000"
